packages:
  - libs/*
  - services/*
onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@cspotcode/source-map-support'
  - '@isaacs/cliui'
  - '@jridgewell/resolve-uri'
  - '@jridgewell/sourcemap-codec'
  - '@jridgewell/trace-mapping'
  - '@lukeed/csprng'
  - '@microsoft/tsdoc'
  - '@nestjs/common'
  - '@nestjs/config'
  - '@nestjs/core'
  - '@nestjs/event-emitter'
  - '@nestjs/mapped-types'
  - '@nestjs/platform-express'
  - '@nestjs/schedule'
  - '@nestjs/swagger'
  - '@nestjs/throttler'
  - '@nestjs/typeorm'
  - '@nuxt/opencollective'
  - '@pkgjs/parseargs'
  - '@scarf/scarf'
  - '@sqltools/formatter'
  - '@swc/core'
  - '@swc/core-win32-x64-msvc'
  - '@swc/counter'
  - '@swc/helpers'
  - '@swc/types'
  - '@tsconfig/node10'
  - '@tsconfig/node12'
  - '@tsconfig/node14'
  - '@tsconfig/node16'
  - '@types/luxon'
  - '@types/node'
  - '@types/validator'
  - accepts
  - acorn
  - acorn-walk
  - ansi-regex
  - ansi-styles
  - ansis
  - app-root-path
  - append-field
  - arg
  - argparse
  - balanced-match
  - base64-js
  - better-sqlite3
  - bindings
  - bl
  - body-parser
  - brace-expansion
  - buffer
  - buffer-from
  - busboy
  - bytes
  - call-bind-apply-helpers
  - call-bound
  - chownr
  - class-transformer
  - class-validator
  - cliui
  - color-convert
  - color-name
  - commander
  - concat-stream
  - consola
  - content-disposition
  - content-type
  - cookie
  - cookie-signature
  - core-js
  - core-util-is
  - cors
  - create-require
  - cron
  - cross-spawn
  - dayjs
  - debug
  - decompress-response
  - deep-extend
  - depd
  - destroy
  - detect-libc
  - diff
  - dotenv
  - dotenv-expand
  - dunder-proto
  - eastasianwidth
  - ee-first
  - emoji-regex
  - encodeurl
  - end-of-stream
  - es-define-property
  - es-errors
  - es-object-atoms
  - esbuild
  - escalade
  - escape-html
  - etag
  - eventemitter2
  - expand-template
  - express
  - fast-safe-stringify
  - file-uri-to-path
  - finalhandler
  - foreground-child
  - forwarded
  - fresh
  - fs-constants
  - function-bind
  - get-caller-file
  - get-intrinsic
  - get-proto
  - github-from-package
  - glob
  - gopd
  - has-symbols
  - hasown
  - http-errors
  - iconv-lite
  - ieee754
  - inherits
  - ini
  - ipaddr.js
  - is-fullwidth-code-point
  - is-promise
  - isarray
  - isexe
  - iterare
  - jackspeak
  - js-yaml
  - libphonenumber-js
  - lodash
  - lru-cache
  - luxon
  - make-error
  - math-intrinsics
  - media-typer
  - merge-descriptors
  - methods
  - mime-db
  - mime-types
  - mimic-response
  - minimatch
  - minimist
  - minipass
  - mkdirp
  - mkdirp-classic
  - ms
  - multer
  - napi-build-utils
  - negotiator
  - node-abi
  - nx
  - object-assign
  - object-inspect
  - on-finished
  - once
  - package-json-from-dist
  - parseurl
  - path-key
  - path-scurry
  - path-to-regexp
  - pg
  - pg-cloudflare
  - pg-connection-string
  - pg-int8
  - pg-pool
  - pg-protocol
  - pg-types
  - pgpass
  - postgres-array
  - postgres-bytea
  - postgres-date
  - postgres-interval
  - prebuild-install
  - process-nextick-args
  - proxy-addr
  - pump
  - qs
  - range-parser
  - raw-body
  - rc
  - readable-stream
  - reflect-metadata
  - require-directory
  - router
  - rxjs
  - safe-buffer
  - safer-buffer
  - semver
  - send
  - serve-static
  - setprototypeof
  - sha.js
  - shebang-command
  - shebang-regex
  - side-channel
  - side-channel-list
  - side-channel-map
  - side-channel-weakmap
  - signal-exit
  - simple-concat
  - simple-get
  - split2
  - sql-highlight
  - statuses
  - streamsearch
  - string-width
  - string_decoder
  - strip-ansi
  - strip-json-comments
  - swagger-ui-dist
  - tar-fs
  - tar-stream
  - toidentifier
  - ts-node
  - tslib
  - tunnel-agent
  - type-is
  - typedarray
  - typeorm
  - typescript
  - uid
  - undici-types
  - unpipe
  - util-deprecate
  - utils-merge
  - uuid
  - v8-compile-cache-lib
  - validator
  - vary
  - which
  - wrap-ansi
  - wrappy
  - xtend
  - y18n
  - yargs
  - yargs-parser
  - yn
