packages:
  - libs/*
  - services/*
onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - better-sqlite3
  - core-js
  - esbuild
  - libxmljs
  - nx
  - sqlite3
