import { createThrowers } from './common/create-throwers.js';

/**
 * Mapped throwers
 */
export const {
  Unauthorized: throwUnauthorizedError,
  SessionNotFound: throwSessionNotFoundError,
  InvalidToken: throwInvalidTokenError,
  ExpiredToken: throwExpiredTokenError,
  FileNotFound: throwFileNotFoundError,
  DirectoryNotFound: throwDirectoryNotFoundError,
  OutOfScope: throwOutOfScopeError,
  SystemOffline: throwSystemOfflineError,
  LowLatency: throwLowLatencyError,
  RequiredFieldMissing: throwRequiredFieldMissingError,
  InvalidString: throwInvalidStringError,
  InvalidNumber: throwInvalidNumberError,
  InvalidInteger: throwInvalidIntegerError,
  InvalidBoolean: throwInvalidBooleanError,
  InvalidObject: throwInvalidObjectError,
  InvalidArray: throwInvalidArrayError,
  InvalidArrayString: throwInvalidArrayStringError,
  InvalidArrayNumber: throwInvalidArrayNumberError,
  InvalidArrayInteger: throwInvalidArrayIntegerError,
  InvalidArrayBoolean: throwInvalidArrayBooleanError,
  InvalidArrayObject: throwInvalidArrayObjectError,
  RequiredString: throwRequiredStringError,
  RequiredNumber: throwRequiredNumberError,
  RequiredInteger: throwRequiredIntegerError,
  RequiredBoolean: throwRequiredBooleanError,
  RequiredObject: throwRequiredObjectError,
  RequiredArray: throwRequiredArrayError,
  EmptyField: throwEmptyFieldError,
  EmptyString: throwEmptyStringError,
  EmptyNumber: throwEmptyNumberError,
  EmptyInteger: throwEmptyIntegerError,
  EmptyBoolean: throwEmptyBooleanError,
  EmptyObject: throwEmptyObjectError,
  EmptyArray: throwEmptyArrayError,
  InvalidField: throwInvalidFieldError,
  MinLength: throwMinLengthError,
  MaxLength: throwMaxLengthError,
  MinNumber: throwMinNumberError,
  MaxNumber: throwMaxNumberError,
  MinArraySize: throwMinArraySizeError,
  MaxArraySize: throwMaxArraySizeError,
  MissingProperty: throwMissingPropertyError,
  MinProperties: throwMinPropertiesError,
  MaxProperties: throwMaxPropertiesError,
} = createThrowers();
